### ISSUE TITLE
Shift Option to Change Default Folder while Creating DocType

### ISSUE THREAD

**Issue by chechani** [pibico/pibiDAV#6]
### Suggestion for flexibility 
Default Folder Setting should be set in for a Doctype NC Setting, However for a particular transaction whether to use Default Folder Setting or Not should be the option while creating the document. Default Folder should be prefilled based on the DOCtype folder setting and A checkbox should be given like " Set Different Folder" then we can prompt to select the folder for NC Brower.

This can be structured in the best possible manner as you can perceive

**Comment by pibico** [comment]
Why do you need to include a nex checkbox Set Different Folder?. If you wish to select a folder different than the default folder just uncheck and check again NC_Enable, NC Browser pop up dialog is triggered to select the new destination folder.

**Comment by pibico** [comment]
The problem here is the way we select the folder and save in the form. If we change the default folder, then to keep the changes on the form we must save and in that case we create the record. This check box could be valid for changing the default folder but after saving it for files to upload to different folder. With the actual logic I do not see how to change the default folder other than changing it in nextcloud settings

**Comment by chechani** [comment]
Ok, Pls Keep it pending, we will explore as suggested and share our experience
